### ISSUE TITLE
The lighthouse API import fails due to wrongly send attributes (base64 encoding errors)

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.webcomponents#103]
We need to make sure that the stats get updated. So if the API calls return an error, we need to show that in the log. And the scheduler should try to get data until the first valid response, not just try ones or even not one time since the flag is set to false initially.

Google told me to set a referrer for security, but the API call does not send one, so we should also add that to each lighthouse request, and set it in the API console of Google.

**UPDATE 2021-07-23**
We decided to always only send the default configuration to the lighthouse backend, same for backend (=stats in detail view) and frontend (=links in detail view)

**Comment by SirCotare** [comment]
I have slightly improved the error reporting.

To make the system (re-)import lighthouse stats, you can use the following admin routes:
PATCH /admin/webcomponent/refetch-lighthouse
PATCH /admin/webcomponent/{uuid}/{versionTag}/metrics

The first one marks all for import and the second one marks only a specific webcomponent version.

The scheduler always sets the flag to false if lighthouse returns an error (an error that is not due to connectivity issues). This is because those errors are mostly the result of a webcomponent not rendering due to issues with the webcomponent itself. Subsequent calls to the lighthouse API will not improve the issue. Therefore we avoid fetching the same errors over and over again.

As far as the "referrer" is concerned, this can not be set when the backend system is crawling the API. This would only be relevant if our frontend was making async calls to the api. From what I see in my personal google console, there should be an option to whitelist server IPs though. So you would have the specify the IP of the backend-server there.

**Comment by Piiit** [comment]
@SirCotare Most lighthouse calls do not work, because you are using the old deprecated preview method, which has been replaced by your new fullscreen preview and base64 encoding afaik.

Example call that does not work:
https://api.webcomponents.opendatahub.testingmachine.eu/preview/0e5fbede-4a21-4dd3-bf85-7d2be71dfb12/development-8-20210416T1559?attribs=lat=%2246.4983%22;lon=%2211.3548%22;zoom=%2210%22;radius=%22%22;language=%22en%22;showradius=%22false%22;category-filter=%22%22;directions=%22true%22

If you need to use the old preview, we need to fix it...

**Comment by Piiit** [comment]
I am currently unable to test this, because most lighthouse calls end in errors...

**Comment by Piiit** [comment]
@SirCotare Still not working in some cases... for example

https://api.webcomponents.opendatahub.testingmachine.eu/preview/1cba7d30-8331-4b4a-b528-c4e03279365c/v1.0.3?attribs=PHdlYmNvbXAtZXZlbnRzIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjUwMHB4IiBsYW5ndWFnZT0iZW4iIG1vZGFsaXR5PSJtYXAiIGZvbnRGYW1pbHk9IkFyaWFsIiBjdXJyZW50TG9jYXRpb249J3sgImxhdCI6IDQ2LjMxLCAibG5nIjogMTEuMjYgfScgbWFwQXR0cmlidXRpb249Ik1hcCBUaWxlcyAmY29weTsgPGEgaHJlZj0naHR0cDovL2RldmVsb3Blci5oZXJlLmNvbSc%20SEVSRTwvYT4iIHRpbGVzLXVybD0iaHR0cHM6Ly8xLmJhc2UubWFwcy5scy5oZXJlYXBpLmNvbS9tYXB0aWxlLzIuMS9tYXB0aWxlL25ld2VzdC9ub3JtYWwuZGF5L3t6fS97eH0ve3l9LzI1Ni9wbmc4P2FwaUtleT0iIGZpbHRlclJhZGl1cz0iNSIgZGlzYWJsZUV2ZW50RGlyZWN0aW9ucyBjYXRlZ29yaWVzRmlsdGVyPSJbXSI%20PC93ZWJjb21wLWV2ZW50cz4%3D

gets send to the lighthouse api, which results in a 

{"errorCode":500,"message":"Illegal base64 character 20","stacktrace":""}

The same example thou, generates the correct base64 encoding clicking on the "Mobile perf." link...

**Comment by Piiit** [comment]
Tested this with the direct links on the detail view and with automated lighthouse calls internally...

1) Some direct links do not work, even thou the statistics are there (so maybe the backend and frontend urls for previews are different?)

For example: https://webcomponents.opendatahub.testingmachine.eu/webcomponent/1cba7d30-8331-4b4a-b528-c4e03279365c/development-8-20210428T1618

2) Many preview calls return with a 404 error --> 
[api-404-errors.txt.tar.gz](https://github.com/noi-techpark/it.bz.opendatahub.webcomponents/files/6868772/api-404-errors.txt.tar.gz)

**Comment by Piiit** [comment]
[api-404-errors.txt.zip](https://github.com/noi-techpark/it.bz.opendatahub.webcomponents/files/6869135/api-404-errors.txt.zip)

**Comment by Piiit** [comment]
Seems to work, thanks
